import { initializeApp, deleteApp } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-app.js";
import { getFirestore, collection, addDoc, updateDoc, deleteDoc, doc, setDoc, getDoc, getDocs, serverTimestamp, query, orderBy, onSnapshot, enableIndexedDbPersistence
} from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged, createUserWithEmailAndPassword, sendPasswordResetEmail, setPersistence, browserSessionPersistence
} from "https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js"; console.log("[Brinka] app.js limpo carregado"); const noteValues = [500, 200, 100, 50, 20, 10, 5];
const coinValues = [2, 1, 0.5, 0.2, 0.1, 0.05, 0.02, 0.01]; const defaultStoreProfiles = [ { id: "loja_1", name: "Loja 1" }, { id: "loja_2", name: "Loja 2" }, { id: "loja_3", name: "Loja 3" }, { id: "loja_4", name: "Loja 4" }
]; let storeProfiles = [...defaultStoreProfiles]; const SUPER_ADMIN_EMAILS = ["admin-brinka@gmail.com", "pica.fern@gmail.com"]; const state = { closures: [], settings: { activeStoreId: "loja_1", defaultExpected: "", theme: "dark" }, db: null, auth: null, firebase: false, unsubscribe: null, usersUnsubscribe: null, activityRefreshTimer: null, presenceTimer: null, user: null, profile: null
}; const $ = (id) => document.getElementById(id); function eur(value) { return new Intl.NumberFormat("pt-PT", { style: "currency", currency: "EUR" }).format(Number(value || 0));
} function makeId() { return crypto?.randomUUID ? crypto.randomUUID() : String(Date.now() + Math.random());
} function toast(text) { const el = $("toast"); if (!el) return; el.textContent = text; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 2300);
} function setStatus(mode, text, sub) { if ($("storageStatus")) $("storageStatus").textContent = text; if ($("syncStatus")) $("syncStatus").textContent = sub; if ($("statusDot")) { $("statusDot").classList.remove("off", "err"); if (mode === "local") $("statusDot").classList.add("off"); if (mode === "error") $("statusDot").classList.add("err"); } if ($("firebaseInfo")) $("firebaseInfo").textContent = ` min`; if (min < 60) return `Visto há  async function updateMyPresence(isOnline = true) { if (!state.db || !state.user) return; const activePage = document.querySelector(".page.active")?.id?.replace("page-", "") || "dashboard"; const device = /iPhone|iPad|Android/i.test(navigator.userAgent) ? "mobile" : "desktop/web"; try { await setDoc(doc(state.db, "users", state.user.uid), { online: isOnline, lastSeenMs: Date.now(), updatedAt: Date.now(), currentLojaId: getActiveStoreId(), currentLojaName: getActiveStoreName(), currentPage: activePage, device }, { merge: true }); } catch (error) { console.warn("[Brinka] Presence erro:", error); }
} function startPresenceSystem() { updateMyPresence(true); if (state.presenceTimer) clearInterval(state.presenceTimer); state.presenceTimer = setInterval(() => updateMyPresence(true), 5000); window.addEventListener("beforeunload", () => updateMyPresence(false), { once: true });
} async function loadStoreNamesRemote() { if (!state.db) return; try { const snap = await getDoc(lojasConfigDocRef()); if (snap.exists() && Array.isArray(snap.data().lojas)) { const remote = snap.data().lojas; storeProfiles = defaultStoreProfiles.map(def => { const found = remote.find(s => s.id === def.id); return found ? { ...def, name: found.name || def.name } : def; }); saveLocal(); } } catch (error) { console.warn("[Brinka] lojas config:", error); }
} async function saveStoreNames() { if (!isAdmin()) { toast("Só admin pode editar lojas"); return; } storeProfiles = defaultStoreProfiles.map(s => ({ ...s, name: $(`storeName_, { merge: true }); } catch (error) { console.warn("[Brinka] backup:", error); }
} async function startStoreListener() { if (state.unsubscribe) state.unsubscribe(); if (!state.db || !state.user) return; setStatus("online", "Firebase ativo", `A carregar  return { notes, coins, notesTotal, coinsTotal, total, expected, diff, initialValue, profit };
} function getDiffLevel(diff) { const value = Math.abs(Number(diff || 0)); if (value < 0.005) return "ok"; if (value <= 5) return "warning"; return "danger";
} function getDiffLabel(diff) { const level = getDiffLevel(diff); if (level === "ok") return "Certo"; if (level === "warning") return ""; return "";
} function validateDiffBeforeSave(calc) { const diffAbs = Math.abs(Number(calc.diff || 0)); const obs = $("obs")?.value.trim() || ""; if (Number(calc.expected || 0) > 0 && diffAbs >= 0.005 && obs.length < 3) { toast("Tens diferença de caixa. Mete uma observação."); $("obs")?.focus(); return false; } if (diffAbs > 20 && !confirm(` de . Queres guardar?`)) return false; return true;
} async function saveClosure() { if (!state.user) return toast("Tens de fazer login"); if (!canCreateFechos()) return toast("Sem permissão para criar fechos"); const calc = calculate(); if (calc.total <= 0) return toast("Mete valores antes de guardar"); if (!validateDiffBeforeSave(calc)) return; const dateIso = $("closeDate")?.value ? new Date($("closeDate").value).toISOString() : new Date().toISOString(); const item = { localId: makeId(), dateIso, dateLabel: new Date(dateIso).toLocaleString("pt-PT", { dateStyle: "short", timeStyle: "short" }), lojaId: getActiveStoreId(), store: getActiveStoreName(), operator: state.profile?.nome || state.user.email, operatorUid: state.user.uid, operatorEmail: state.user.email, role: state.profile?.role || "user", expected: calc.expected, previousTotal: calc.expected, initialValue: calc.initialValue, profit: calc.profit, diff: calc.diff, diffLevel: getDiffLevel(calc.diff), diffLabel: getDiffLabel(calc.diff), total: calc.total, notesTotal: calc.notesTotal, coinsTotal: calc.coinsTotal, notes: calc.notes, coins: calc.coins, observation: $("obs")?.value.trim() || "", createdAt: serverTimestamp(), updatedAt: serverTimestamp() }; try { await addDoc(fechosCollection(), item); clearForm(false); toast("Fecho guardado"); } catch (error) { console.error(error); toast("Erro ao guardar"); }
} function clearForm(show = true) { document.querySelectorAll(".money-row input").forEach(i => i.value = ""); if ($("store")) $("store").value = getActiveStoreId(); setExpectedFromPrevious(); if ($("initialValue")) $("initialValue").value = ""; if ($("obs")) $("obs").value = ""; setNowDate(); calculate(); if (show) toast("Formulário limpo");
} function toDateTimeLocalValue(dateIso) { if (!dateIso) return ""; const d = new Date(dateIso); if (Number.isNaN(d.getTime())) return ""; d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0, 16);
} function openEditClosure(id) { const item = state.closures.find(i => (i.id || i.localId) === id); if (!item) return toast("Fecho não encontrado"); const previous = getPreviousClosureValue(id, item.dateIso); if ($("editClosureId")) $("editClosureId").value = id; if ($("editOperator")) $("editOperator").value = item.operator || ""; if ($("editDate")) $("editDate").value = toDateTimeLocalValue(item.dateIso); if ($("editTotal")) $("editTotal").value = Number(item.total || 0).toFixed(2); if ($("editInitialValue")) $("editInitialValue").value = Number(item.initialValue || 0).toFixed(2); if ($("editPrevious")) $("editPrevious").value = previous ? previous.toFixed(2) : "0.00"; if ($("editObs")) $("editObs").value = item.observation || ""; $("editClosureModal")?.classList.remove("hidden"); $("editClosureModal")?.setAttribute("aria-hidden", "false");
} function closeEditClosure() { $("editClosureModal")?.classList.add("hidden"); $("editClosureModal")?.setAttribute("aria-hidden", "true");
} async function saveEditedClosure() { const id = $("editClosureId")?.value; const total = Number($("editTotal")?.value || 0); const initialValue = Number($("editInitialValue")?.value || 0); const profit = total - initialValue; try { await updateDoc( doc(state.db, "brinka_lojas", getActiveStoreId(), "fechos", id), { total, initialValue, profit, updatedAt: serverTimestamp() } ); closeEditClosure(); toast("Fecho atualizado"); } catch (e) { console.error("ERRO AO EDITAR:", e); alert("Erro ao editar: " + e.message); }
} async function deleteClosure(id) { if (!canDeleteFechos()) return toast("Sem permissão"); try { await deleteDoc(doc(state.db, "brinka_lojas", getActiveStoreId(), "fechos", id)); toast("Fecho apagado"); } catch (error) { console.error(error); toast("Erro ao apagar"); }
} function getDayKeyFromIso(dateIso) { const d = dateIso ? new Date(dateIso) : new Date(); return ` else if (diff > 0) { status.textContent = "Subiu"; status.className = "pill profit-good"; } else if (diff < 0) { status.textContent = "Desceu"; status.className = "pill profit-bad"; } else { status.textContent = "Igual"; status.className = "pill profit-neutral"; } } if ($("profitNote")) { if (!hasPrevious) { $("profitNote").textContent = "Ainda não existe fecho de um dia anterior para comparar."; } else { const percent = previous.total > 0 ? ((diff / previous.total) * 100) : 0; $("profitNote").textContent = `
} function renderDashboard() { const today = new Date().toLocaleDateString("pt-PT"); const todayItems = state.closures.filter(i => i.dateIso && new Date(i.dateIso).toLocaleDateString("pt-PT") === today); const todayTotal = todayItems.reduce((sum, i) => sum + Number(i.total || 0), 0); const todayDiff = todayItems.reduce((sum, i) => sum + Number(i.diff || 0), 0); const allTotal = state.closures.reduce((sum, i) => sum + Number(i.total || 0), 0); const best = Math.max(0, ...state.closures.map(i => Number(i.total || 0))); const avg = state.closures.length ? allTotal / state.closures.length : 0; if ($("todayTotal")) $("todayTotal").textContent = eur(todayTotal); if ($("todayDiff")) $("todayDiff").textContent = eur(todayDiff); if ($("todaySubtitle")) $("todaySubtitle").textContent = `</b><br><span class="muted"></span></div> </div> `).join("") || `<p class="muted">Ainda não existem fechos guardados nesta loja.</p>`; } renderSmartDashboard(); renderProfitDashboard(); renderMultiLojaResumo();
} function dateKeyFromDate(date) { const d = new Date(date); return `%`; if ($("smartTodayVsAvg")) $("smartTodayVsAvg").textContent = "0%"; if ($("dashHealth")) $("dashHealth").textContent = items.length ? "Ativo" : "Sem dados"; const days = []; for (let i = 6; i >= 0; i--) { const d = new Date(); d.setDate(d.getDate() - i); const key = dateKeyFromDate(d); const dayTotal = items.filter(x => x.dateIso && dateKeyFromDate(x.dateIso) === key).reduce((s, x) => s + Number(x.total || 0), 0); days.push({ label: d.toLocaleDateString("pt-PT", { weekday: "short" }).replace(".", ""), total: dayTotal }); } const maxDay = Math.max(1, ...days.map(d => d.total)); const total7 = days.reduce((s, d) => s + d.total, 0); if ($("chartTotal7")) $("chartTotal7").textContent = eur(total7); if ($("weekChart")) { $("weekChart").innerHTML = days.map(day => `<div class="bar-day"><div class="bar-track"><div class="bar-fill" style="height:); $("historyTable").innerHTML = items.map(i => ` <tr> <td>"> · </span></td> <td class="action-buttons"> <button class="mini-btn action-edit" data-edit="</strong><br><span class="muted"></span></div></div>`).join("") || `<p class="muted">Sem dados.</p>`;
} function populateStoreSelects() { const options = storeProfiles.map(s => `<option value=""`).join(";")); const blob = new Blob([[header.join(";"), ...rows].join("\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `brinka-${getActiveStoreId()}-historico.csv`; link.click(); URL.revokeObjectURL(link.href);
} function startActivityRefresh() { if (state.activityRefreshTimer) clearInterval(state.activityRefreshTimer); state.activityRefreshTimer = setInterval(() => { if (isAdmin() && document.querySelector("#page-users.active")) { loadUsers(); } }, 10000);
} function startUsersOnlineListener() { if (!isAdmin() || !state.db) return; if (state.usersUnsubscribe) state.usersUnsubscribe(); state.usersUnsubscribe = onSnapshot(usersCollection(), snap => { renderUsersList(snap.docs.map(d => ({ uid: d.id, ...d.data() }))); }, error => { console.error(error); if ($("usersList")) $("usersList").innerHTML = `<p class="muted">Erro ao carregar utilizadores.</p>`; });
} async function loadUsers() { if (!isAdmin() || !state.db) return; try { const snap = await getDocs(usersCollection()); renderUsersList(snap.docs.map(d => ({ uid: d.id, ...d.data() }))); } catch (error) { console.error(error); }
} function renderUsersList(users) { const onlineCount = users.filter(isUserOnline).length; if ($("onlineSummary")) $("onlineSummary").textContent = `Online agora: ${onlineCount}`; if (!$("usersList")) return; $("usersList").innerHTML = users.map(u => { const lojaName = storeProfiles.find(s => s.id === u.lojaId)?.name || u.lojaId || "—"; const pClass = presenceClass(u); return ` <div class="user-card"> <div class="user-card-top"> <div> <strong>${u.nome || "Sem nome"}</strong><br> <small>${u.email || "Sem email"}</small><br> <small>UID: ${u.uid}</small> </div> <span class="pill">${u.role || "user"}</span> </div> <div class="user-chip-row"> <span class="user-chip ${pClass}"><span class="${pClass}-dot"></span>${lastSeenText(u)}</span> <span class="user-chip">Loja: ${u.currentLojaName || lojaName}</span> <span class="user-chip">Página: ${u.currentPage || "—"}</span> <span class="user-chip">Dispositivo: ${u.device || "—"}</span> <span class="user-chip">${u.ativo === false ? "Bloqueado" : "Ativo"}</span> </div> <div class="user-actions"> <button class="mini-btn" data-edit-user="${u.uid}">Editar</button> <button class="mini-btn" data-reset-user="${u.email || ""}">Reset password</button> <button class="mini-btn danger" data-delete-user="${u.uid}">Apagar perfil</button> </div> </div> `; }).join("") || `<p class="muted">Ainda não existem perfis.</p>`; document.querySelectorAll("[data-edit-user]").forEach(btn => btn.addEventListener("click", () => { const u = users.find(x => x.uid === btn.dataset.editUser); if (!u) return; $("userUid").value = u.uid || ""; $("userName").value = u.nome || ""; $("userEmail").value = u.email || ""; $("userRole").value = u.role || "user"; $("userStore").value = u.lojaId || "loja_1"; })); document.querySelectorAll("[data-reset-user]").forEach(btn => btn.addEventListener("click", async () => { if (!btn.dataset.resetUser) return; try { await sendPasswordResetEmail(state.auth, btn.dataset.resetUser); toast("Email de reset enviado"); } catch { toast("Erro ao enviar reset"); } })); document.querySelectorAll("[data-delete-user]").forEach(btn => btn.addEventListener("click", async () => { if (!confirm("Apagar este perfil?")) return; try { await deleteDoc(doc(state.db, "users", btn.dataset.deleteUser)); toast("Perfil apagado"); } catch { toast("Erro ao apagar perfil"); } }));
} function clearUserForm() { if ($("userUid")) $("userUid").value = ""; if ($("userName")) $("userName").value = ""; if ($("userEmail")) $("userEmail").value = ""; if ($("userRole")) $("userRole").value = "user"; if ($("userStore")) $("userStore").value = "loja_1";
} async function createAuthUserAndFillUid() { if (!isAdmin()) return toast("Só admin pode criar users"); const email = $("newAuthEmail")?.value.trim(); const password = $("newAuthPassword")?.value; if (!email || !password || password.length < 6) return toast("Email/password inválidos"); let secondaryApp = null; try { secondaryApp = initializeApp(window.BRINKA_FIREBASE_CONFIG, `secondary-${Date.now()}`); const secondaryAuth = getAuth(secondaryApp); const cred = await createUserWithEmailAndPassword(secondaryAuth, email, password); $("userUid").value = cred.user.uid; $("userEmail").value = email; $("userName").value = email.split("@")[0]; await signOut(secondaryAuth); await deleteApp(secondaryApp); toast("Login criado. Agora guarda perfil."); } catch (error) { console.error(error); try { if (secondaryApp) await deleteApp(secondaryApp); } catch {} toast(error.code === "auth/email-already-in-use" ? "Email já existe" : "Erro ao criar login"); }
} async function saveUserProfile() { if (!isAdmin()) return toast("Só admin"); const uid = $("userUid")?.value.trim(); const nome = $("userName")?.value.trim(); const email = $("userEmail")?.value.trim(); const role = $("userRole")?.value || "user"; const lojaId = $("userStore")?.value || "loja_1"; if (!uid || !nome || !email) return toast("Preenche UID, nome e email"); try { await setDoc(doc(state.db, "users", uid), { nome, email, role, lojaId, ativo: true, updatedAt: Date.now() }, { merge: true }); clearUserForm(); toast("Perfil guardado"); } catch (error) { console.error(error); toast("Erro ao guardar perfil"); }
} function bindEvents() { document.querySelectorAll("[data-page]").forEach(b => b.addEventListener("click", () => switchPage(b.dataset.page))); $("menuBtn")?.addEventListener("click", () => { $("sidebar")?.classList.add("open"); $("overlay")?.classList.add("show"); }); $("overlay")?.addEventListener("click", () => { $("sidebar")?.classList.remove("open"); $("overlay")?.classList.remove("show"); }); $("loginBtn")?.addEventListener("click", doLogin); $("loginPassword")?.addEventListener("keydown", e => { if (e.key === "Enter") doLogin(); }); $("logoutBtn")?.addEventListener("click", doLogout); $("themeBtn")?.addEventListener("click", () => { state.settings.theme = state.settings.theme === "light" ? "dark" : "light"; saveLocal(); renderSettings(); }); $("expected")?.addEventListener("input", calculate); $("initialValue")?.addEventListener("input", calculate); $("saveClosure")?.addEventListener("click", saveClosure); $("clearForm")?.addEventListener("click", () => clearForm(true)); $("search")?.addEventListener("input", renderHistory); $("statusFilter")?.addEventListener("change", renderHistory); $("exportCsv")?.addEventListener("click", exportCsv); $("saveSettings")?.addEventListener("click", saveSettings); $("saveStoreNames")?.addEventListener("click", saveStoreNames); $("store")?.addEventListener("change", () => changeActiveStore($("store").value)); $("activeStore")?.addEventListener("change", () => changeActiveStore($("activeStore").value)); $("saveUserProfile")?.addEventListener("click", saveUserProfile); $("clearUserForm")?.addEventListener("click", clearUserForm); $("refreshUsers")?.addEventListener("click", loadUsers); $("createAuthUserBtn")?.addEventListener("click", createAuthUserAndFillUid); $("closeEditClosure")?.addEventListener("click", closeEditClosure); $("cancelEditClosure")?.addEventListener("click", closeEditClosure); $("saveEditClosure")?.addEventListener("click", saveEditedClosure); } document.addEventListener("click", event => { if (event.target.closest?.("#loginBtn")) { event.preventDefault(); doLogin(); }
}); async function init() { loadLocal(); buildMoneyRows("notesRows", noteValues); buildMoneyRows("coinsRows", coinValues); bindEvents(); loadRememberedEmail(); setNowDate(); calculate(); renderAll(); const ok = await initFirebaseCore(); if (!ok) { showLogin(true); return; } onAuthStateChanged(state.auth, async user => { if (user) await afterLogin(user); else { showLogin(true); setStatus("local", "Sem login", "Entra para sincronizar"); } });
} init();
